services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
